### ISSUE TITLE
Error when changed android sdk to 32

### ISSUE THREAD

**Issue by lionheart83** [anggastudio/Printama#12]
Please help me! when i changed to android studio debugger says : * What went wrong:
Execution failed for task ':printama:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by anggastudio** [comment]
just released the 0.9.73 version for Android 13 and above

> java 17
> min SDK 19
> Bluetooth permission handler please see the sample app
