### ISSUE TITLE
print full bitmap image 

### ISSUE THREAD

**Issue by laithbzour** [anggastudio/Printama#13]
when i try to print full bitmap image in 58mm printer 
print Chinese char

**Comment by anggastudio** [comment]
could you please provide the code,
and print result

**Comment by laithbzour** [comment]
@anggastudio thanks for response 
this my code 
-----------------------------------
   int targetWidth = 300;
                Bitmap rescaledBitmap = Bitmap.createScaledBitmap(
                        bytes,
                        targetWidth,
                        Math.round(((float) bytes.getHeight()) * ((float) targetWidth) / ((float) bytes.getWidth())),
                        true
                );
                Printama.with(context).connect(printama -> {
                    printama.printImage(rescaledBitmap,300);
                    printama.close();
                });

**Comment by laithbzour** [comment]
![b9bb775d-4749-49f9-bfb1-292d2f6627e5](https://user-images.githubusercontent.com/14046215/180933456-3760eb5a-98a7-45d8-a324-f2eeb0bdb6d8.jpeg)

**Comment by laithbzour** [comment]
my printer specification 
Paper Width: 58mm
Diameter: 40mm

**Comment by anggastudio** [comment]
to make sure the rescaledBitmap is correct -> display it first using ImageView.

it happened when the bitmap is corrupt after rescaled,
or
don't rescaled it, just use` printama.printImage(originalBitmap, 300);`

**Comment by laithbzour** [comment]
@anggastudio 
i try same issue (print Chinese char) when just use printama.printImage(originalBitmap, 300);
my originalBitmap dim = 384 *301

how can print it please can help

**Comment by anggastudio** [comment]
have you try to NOT use this code
`printama.close();`
may be the stream is truncated when printer closed

**Comment by laithbzour** [comment]
@anggastudio 
give me  : java.lang.RuntimeException: Buffer not large enough for pixels

**Comment by laithbzour** [comment]
@anggastudio  can print arabic text ??

**Comment by anggastudio** [comment]
no, not yet

**Comment by laithbzour** [comment]
@anggastudio when i split image to chunk (374 *31) its print one image ... second no when set time out for printing line (300ms) print one and two three no ??  whats is problem here ??

**Comment by laithbzour** [comment]
@anggastudio 
thanks for your support i find the issue is in black color intensity on bitmap image
