### ISSUE TITLE
Printed Images Changing into Unreadable Character

### ISSUE THREAD

**Issue by Fizhu** [anggastudio/Printama#5]
#### How its happened
Before this happened, I tried to print an image (logo) with several text below it, and its works verry well with no issue, but after I added QR Code (Bitmap) to be printed with, the logo just printed half and half more becomes unreadable character (image below)

Here it is the code that i used for :
```kt
val logo = Printama.getBitmapFromVector(activity, R.drawable.logo_black)
val nota = "Some Text"
Printama.with(activity).connect({ printama: Printama ->
      printama.printImage(logo, 200)
      printama.addNewLine()
      printama.printTextln(Printama.CENTER, "Title Text")
      printama.setNormalText()
      printama.printTextln(
          Printama.CENTER,
          "Some Text"
      )
    printama.printDashedLine()

    val writer = QRCodeWriter()
    val bitMatrix = writer.encode(nota, BarcodeFormat.QR_CODE, 300, 300)
    val width = bitMatrix.width
    val height = bitMatrix.height
    val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.RGB_565)
    for (x in 0 until width) {
        for (y in 0 until height) {
            bitmap.setPixel(x, y, if (bitMatrix.get(x, y)) Color.BLACK else Color.WHITE)
        }
    }

    bitmap?.let {
        printama.printImage(it)
    }

    printama.addNewLine()
    printama.feedPaper()
    printama.close()
}) { message: String? -> activity.toast(message) }
```

![WhatsApp Image 2021-04-25 at 15 47 42](https://user-images.githubusercontent.com/22523372/115987047-9e78bb80-a5dd-11eb-8b0c-1368dc95fe29.jpeg)

**Comment by anggastudio** [comment]
You should print add new line before printing the image. I see the outstream is merged between the dashed line and bitmap stream

**printama.addNewLine();**
printama.printImage(......);

do that if only issue appear.
I will do some more research later.

The code you are trying to execute is available in the sample app

![image](https://user-images.githubusercontent.com/18232138/122520053-5e621200-d03d-11eb-8ac9-bdfe3b1330e7.png)
