### ISSUE TITLE
Build error after adding the gradles

### ISSUE THREAD

**Issue by m-darwich** [anggastudio/Printama#7]
Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.anggastudio:Printama:0.9.7.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/anggastudio/Printama/0.9.7/Printama-0.9.7.pom
       - https://repo.maven.apache.org/maven2/com/github/anggastudio/Printama/0.9.7/Printama-0.9.7.pom
       - https://jcenter.bintray.com/com/github/anggastudio/Printama/0.9.7/Printama-0.9.7.pom
     Required by:
         project :app

**Comment by anggastudio** [comment]
Can you give me more detailed information.

I think I should remove maven installation.

**Comment by anggastudio** [comment]
close this due to lack of information of the issue
