### ISSUE TITLE
How can I set bitmap/image width as printer's paper width?

### ISSUE THREAD

**Issue by tohedul** [anggastudio/Printama#8]
Hi, I just mailed you about this issue.

You set PRINTER_WIDTH = 384 (which is fixed). That doesn't care about the actual printer paper width. Instead of that, can't we detect printer paper size from socket data? or you can add a paper size option on choose printer dialog. So, if we set 58mm/80mm/custom width, then it will be used as printer width throughout the app for that selected printer.

**Comment by anggastudio** [comment]
not tested yet for 3" printer.
I'll add the method to set it later, thanks

**Comment by anggastudio** [comment]
I am closing this,
will added to roadmap for 3 inches printer
